openapi: 3.1.0
info:
  title: QAUserSearch - Schema Extraction API
  description: |
    API para extração automática de schemas de bancos externos, 
    persistência no catálogo local e enriquecimento via LLM.
  version: 1.0.0
  contact:
    name: QAUserSearch Team

servers:
  - url: http://localhost:8000/api/v1
    description: Development server
  - url: https://qausersearch.internal/api/v1
    description: Production server

tags:
  - name: Sources
    description: Operações em fontes de dados externas
  - name: Columns
    description: Operações em metadados de colunas
  - name: Extraction
    description: Operações de extração de schema
  - name: Enrichment
    description: Operações de enriquecimento via LLM

paths:
  /sources:
    get:
      tags: [Sources]
      summary: Listar fontes catalogadas
      description: Retorna todas as fontes de dados externas catalogadas no sistema
      operationId: listSources
      parameters:
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/ExtractionStatus'
          description: Filtrar por status de extração
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Lista de fontes catalogadas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSourcesResponse'
        '422':
          $ref: '#/components/responses/ValidationError'

  /sources/{source_id}:
    get:
      tags: [Sources]
      summary: Obter detalhes de uma fonte
      description: Retorna informações detalhadas de uma fonte específica
      operationId: getSource
      parameters:
        - $ref: '#/components/parameters/SourceId'
      responses:
        '200':
          description: Detalhes da fonte
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SourceDetailResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /sources/{source_id}/columns:
    get:
      tags: [Columns]
      summary: Listar colunas de uma fonte
      description: Retorna todas as colunas catalogadas para uma fonte específica
      operationId: listSourceColumns
      parameters:
        - $ref: '#/components/parameters/SourceId'
        - name: is_required
          in: query
          schema:
            type: boolean
          description: Filtrar por campos obrigatórios/opcionais
        - name: is_enumerable
          in: query
          schema:
            type: boolean
          description: Filtrar por campos enumeráveis
        - name: enrichment_status
          in: query
          schema:
            $ref: '#/components/schemas/EnrichmentStatus'
          description: Filtrar por status de enriquecimento
        - name: parent_path
          in: query
          schema:
            type: string
          description: Filtrar por path do objeto pai (campos aninhados)
      responses:
        '200':
          description: Lista de colunas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ColumnsResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /extraction:
    post:
      tags: [Extraction]
      summary: Iniciar extração de schema
      description: |
        Inicia o processo de extração de schema para uma fonte externa.
        O processo analisa amostras de documentos e infere tipos, 
        campos obrigatórios/opcionais e colunas enumeráveis.
      operationId: startExtraction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtractionRequest'
      responses:
        '202':
          description: Extração iniciada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractionStartedResponse'
        '409':
          description: Extração já em andamento para esta fonte
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          $ref: '#/components/responses/ValidationError'

  /extraction/{source_id}/status:
    get:
      tags: [Extraction]
      summary: Verificar status da extração
      description: Retorna o status atual do processo de extração
      operationId: getExtractionStatus
      parameters:
        - $ref: '#/components/parameters/SourceId'
      responses:
        '200':
          description: Status da extração
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractionStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /enrichment:
    post:
      tags: [Enrichment]
      summary: Iniciar enriquecimento de colunas
      description: |
        Inicia o processo de enriquecimento semântico via LLM.
        Pode processar uma fonte específica ou colunas com status pending_enrichment.
      operationId: startEnrichment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrichmentRequest'
      responses:
        '202':
          description: Enriquecimento iniciado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrichmentStartedResponse'
        '422':
          $ref: '#/components/responses/ValidationError'

  /enrichment/retry:
    post:
      tags: [Enrichment]
      summary: Retry de colunas pending_enrichment
      description: |
        Reprocessa colunas que falharam no enriquecimento anterior.
        Busca automaticamente colunas com status 'pending_enrichment'.
      operationId: retryEnrichment
      responses:
        '202':
          description: Retry iniciado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrichmentRetryResponse'
        '404':
          description: Nenhuma coluna para retry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /catalog/search:
    get:
      tags: [Sources]
      summary: Buscar no catálogo
      description: Busca fontes e colunas por termo (nome, descrição)
      operationId: searchCatalog
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
            minLength: 2
          description: Termo de busca
        - name: type
          in: query
          schema:
            type: string
            enum: [source, column, all]
            default: all
          description: Tipo de resultado
      responses:
        '200':
          description: Resultados da busca
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogSearchResponse'

components:
  parameters:
    SourceId:
      name: source_id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: ID da fonte externa

  schemas:
    # Enums
    ExtractionStatus:
      type: string
      enum: [pending, in_progress, completed, failed]
      description: Status do processo de extração

    EnrichmentStatus:
      type: string
      enum: [pending, enriched, pending_enrichment, skipped]
      description: Status do enriquecimento semântico

    InferredType:
      type: string
      enum: [string, number, integer, boolean, date, array, object, null, unknown]
      description: Tipo de dado inferido

    # Request/Response DTOs
    ExtractionRequest:
      type: object
      required:
        - db_name
        - table_name
      properties:
        db_name:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-z_]+$'
          example: card_account_authorization
          description: Nome do banco externo
        table_name:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^[a-z_]+$'
          example: account_main
          description: Nome da tabela
        sample_size:
          type: integer
          minimum: 10
          maximum: 10000
          default: 500
          description: Número de documentos a analisar (override do padrão)

    ExtractionStartedResponse:
      type: object
      properties:
        source_id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/ExtractionStatus'
        message:
          type: string
          example: Extração iniciada com sucesso
        estimated_documents:
          type: integer
          description: Documentos que serão analisados

    ExtractionStatusResponse:
      type: object
      properties:
        source_id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/ExtractionStatus'
        total_columns:
          type: integer
        progress_percentage:
          type: number
          format: float
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true
        error_message:
          type: string
          nullable: true

    EnrichmentRequest:
      type: object
      properties:
        source_id:
          type: string
          format: uuid
          description: ID da fonte para enriquecer (opcional, se omitido processa pending)
        column_ids:
          type: array
          items:
            type: string
            format: uuid
          description: IDs específicos de colunas (opcional)

    EnrichmentStartedResponse:
      type: object
      properties:
        columns_to_process:
          type: integer
        status:
          type: string
          example: processing
        message:
          type: string

    EnrichmentRetryResponse:
      type: object
      properties:
        columns_retried:
          type: integer
        message:
          type: string

    # Source DTOs
    SourceSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        db_name:
          type: string
        table_name:
          type: string
        extraction_status:
          $ref: '#/components/schemas/ExtractionStatus'
        total_columns:
          type: integer
        enriched_columns:
          type: integer
        updated_at:
          type: string
          format: date-time

    SourceDetailResponse:
      allOf:
        - $ref: '#/components/schemas/SourceSummary'
        - type: object
          properties:
            created_at:
              type: string
              format: date-time
            enrichment_progress:
              type: number
              format: float
              description: Percentual de colunas enriquecidas
            columns_by_type:
              type: object
              additionalProperties:
                type: integer
              description: Contagem de colunas por tipo inferido
            required_columns_count:
              type: integer
            optional_columns_count:
              type: integer
            enumerable_columns_count:
              type: integer

    PaginatedSourcesResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SourceSummary'
        total:
          type: integer
        page:
          type: integer
        page_size:
          type: integer
        pages:
          type: integer

    # Column DTOs
    ColumnMetadataResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        column_name:
          type: string
        column_path:
          type: string
        inferred_type:
          $ref: '#/components/schemas/InferredType'
        is_required:
          type: boolean
        is_enumerable:
          type: boolean
        enumerable_values:
          type: array
          items:
            type: string
          nullable: true
        semantic_description:
          type: string
          nullable: true
        enrichment_status:
          $ref: '#/components/schemas/EnrichmentStatus'
        sample_values:
          type: array
          items: {}
          nullable: true
        parent_path:
          type: string
          nullable: true
        depth:
          type: integer
        occurrence_rate:
          type: number
          format: float

    ColumnsResponse:
      type: object
      properties:
        source_id:
          type: string
          format: uuid
        columns:
          type: array
          items:
            $ref: '#/components/schemas/ColumnMetadataResponse'
        total:
          type: integer

    # Search DTOs
    CatalogSearchResponse:
      type: object
      properties:
        sources:
          type: array
          items:
            $ref: '#/components/schemas/SourceSummary'
        columns:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: '#/components/schemas/ColumnMetadataResponse'
              source:
                $ref: '#/components/schemas/SourceSummary'
        total_results:
          type: integer

    # Error DTOs
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true

    ValidationErrorResponse:
      type: object
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
              msg:
                type: string
              type:
                type: string

  responses:
    NotFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: not_found
            message: Fonte não encontrada

    ValidationError:
      description: Erro de validação
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationErrorResponse'
